# SPDX-License-Identifier: Apache-2.0
"""Machine-readable v0.6 agent guidance and stable local failure catalog."""

from __future__ import annotations

from typing import Final

AGENT_GUIDANCE: Final[dict[str, object]] = {
    "api_version": "cpcf.io/v0.6",
    "native_result": "operational_organization_profile",
    "acceleration_authority": "externally_registered_evidence_only",
    "first_safe_commands": [
        ["cpcf", "agent", "explain", "--json"],
        ["cpcf", "self-check", "--json"],
        ["cpcf", "schema", "list", "--json"],
    ],
    "offline_capabilities": [
        "schema inspection",
        "installation self-check",
        "portable bundle verification",
        "read-only legacy inspection",
        "bounded exact model-conditional growth planning and independent checking",
        "read-only registered growth evidence reassessment",
    ],
    "nonclaims": [
        "collective-superintelligence phase detection or creation",
        "causality or statistical validity",
        "thermodynamic feasibility or physical phase behavior",
        "local process sandboxing",
        "operational assurance without completed release gates",
    ],
}

RUNNER_GATEWAY_ERROR_CODES: Final[frozenset[str]] = frozenset(
    {
        "runner_artifact_budget_exhausted",
        "runner_artifact_digest_invalid",
        "runner_artifact_digest_mismatch",
        "runner_artifact_limit_exceeded",
        "runner_artifact_missing_after_upload",
        "runner_artifact_storage_invariant_failed",
        "runner_artifact_too_large",
        "runner_attempt_limit_exhausted",
        "runner_capability_authority_invalid",
        "runner_certificate_binding_duplicate",
        "runner_certificate_header_invalid",
        "runner_certificate_identity_untrusted",
        "runner_execution_policy_authority_invalid",
        "runner_failure_projection_rejected",
        "runner_heartbeat_sequence_invalid",
        "runner_idempotency_key_reused",
        "runner_idempotency_type_mismatch",
        "runner_identity_not_registered",
        "runner_job_duplicate",
        "runner_job_not_available",
        "runner_job_not_bound",
        "runner_job_signature_invalid",
        "runner_lease_not_found",
        "runner_lease_stale",
        "runner_material_limit_exceeded",
        "runner_material_missing",
        "runner_pending_projection_duplicate",
        "runner_pending_projection_invalid",
        "runner_projection_storage_invariant_failed",
        "runner_receipt_nonconformant",
        "runner_receipt_signature_invalid",
        "runner_receipt_storage_invariant_failed",
        "runner_registration_duplicate",
        "runner_request_schema_invalid",
        "runner_selector_output_invalid",
        "runner_signed_statement_invalid",
    }
)

GROWTH_ERROR_CODES: Final[frozenset[str]] = frozenset(
    {
        "growth_frontier_action_latent",
        "growth_frontier_activation_not_admitted",
        "growth_frontier_advancement_unavailable",
        "growth_frontier_binding_mismatch",
        "growth_frontier_binding_missing",
        "growth_frontier_capability_missing",
        "growth_frontier_condition_invalid",
        "growth_frontier_contract_mismatch",
        "growth_frontier_depth_overflow",
        "growth_frontier_digest_mismatch",
        "growth_frontier_document_required",
        "growth_frontier_evidence_reassessed",
        "growth_frontier_evidence_unavailable",
        "growth_frontier_lineage_invalid",
        "growth_frontier_not_admitted",
        "growth_frontier_object_expired",
        "growth_frontier_object_missing",
        "growth_frontier_object_unavailable",
        "growth_frontier_observation_outside_model",
        "growth_frontier_partition_invalid",
        "growth_frontier_premise_unavailable",
        "growth_frontier_producer_mismatch",
        "growth_frontier_reassessment_inconclusive",
        "growth_frontier_rule_duplicate",
        "growth_frontier_state_mismatch",
        "growth_frontier_state_missing",
        "growth_frontier_successor_ambiguous",
        "growth_frontier_synthetic_example",
        "growth_frontier_target_undeclared",
        "growth_frontier_witness_mismatch",
        "growth_continuation_state_stale",
        "growth_observed_work_blocked",
        "growth_trial_time_origin_mismatch",
        "growth_scalar_endpoint_required",
        "growth_action_duplicate",
        "growth_action_expired",
        "growth_action_missing",
        "growth_backlog_limit",
        "growth_calibration_domain",
        "growth_calibration_invalid",
        "growth_capability_effect",
        "growth_capability_missing",
        "growth_capability_schema",
        "growth_capacity_prerequisite",
        "growth_charge_category",
        "growth_checker_budget",
        "growth_checkpoint_invalid",
        "growth_cli_cas_digest",
        "growth_cli_cas_limit",
        "growth_cli_document_kind",
        "growth_cli_duplicate_object",
        "growth_cli_input_invalid",
        "growth_cli_object_limit",
        "growth_comparator_duplicate",
        "growth_comparison_completed",
        "growth_completion_exceeds_work",
        "growth_completion_late",
        "growth_completion_without_work",
        "growth_contract_inspected",
        "growth_coverage_floor",
        "growth_credit_blocked_by_work",
        "growth_deadline",
        "growth_domain_invalid",
        "growth_domains_mismatch",
        "growth_domains_missing",
        "growth_duplicate_evidence",
        "growth_duration_invalid",
        "growth_evidence_compatible",
        "growth_example_unknown",
        "growth_factor_invalid",
        "growth_hazard",
        "growth_hypothetical_replay",
        "growth_inconsistent_models",
        "growth_interval_invalid",
        "growth_job_not_admitted",
        "growth_model_domain",
        "growth_model_policy_found",
        "growth_negative_quantity",
        "growth_no_guaranteed_entry",
        "growth_nonrepeatable_reuse",
        "growth_object_digest",
        "growth_objective",
        "growth_observation_contract_mismatch",
        "growth_observation_expired",
        "growth_observation_not_admitted",
        "growth_observation_outside_model",
        "growth_observation_seed_mismatch",
        "growth_observation_time_order",
        "growth_observation_trace_incomplete",
        "growth_observation_versions_changed",
        "growth_observation_window_changed",
        "growth_observed_block_not_supported",
        "growth_observed_evidence_pending",
        "growth_plan_action_invalid",
        "growth_plan_branches_invalid",
        "growth_plan_checked",
        "growth_plan_comparison_mismatch",
        "growth_plan_continuation_invalid",
        "growth_plan_digest_mismatch",
        "growth_plan_effect_mismatch",
        "growth_plan_entry_invalid",
        "growth_plan_input_mismatch",
        "growth_plan_objective_mismatch",
        "growth_plan_policy_missing",
        "growth_plan_state_mismatch",
        "growth_plan_terminal_mismatch",
        "growth_premise_expires_during_action",
        "growth_premise_missing_or_expired",
        "growth_proposal_binding_mismatch",
        "growth_proposal_generation_mismatch",
        "growth_proposal_inputs_missing",
        "growth_proposed_external_job",
        "growth_protected_object",
        "growth_quality_floor",
        "growth_queue_domain",
        "growth_reassessment_inconclusive",
        "growth_receipt_action_mismatch",
        "growth_receipt_nonconformant",
        "growth_receipt_not_admitted",
        "growth_receipt_physical_time_mismatch",
        "growth_receipt_principal_mismatch",
        "growth_receipt_time_missing",
        "growth_replan_state_unavailable",
        "growth_replanned_proposal",
        "growth_replay_after_terminal",
        "growth_required_object",
        "growth_required_object_expired",
        "growth_reservation_domain",
        "growth_reservation_expired",
        "growth_resource_domain",
        "growth_resource_floor",
        "growth_runner_materials_not_admitted",
        "growth_service_floor",
        "growth_service_overbooked",
        "growth_shared_resource_double_booking",
        "growth_snapshot_missing",
        "growth_source_missing",
        "growth_source_not_admitted",
        "growth_source_receipt_mismatch",
        "growth_successor_duplicate",
        "growth_successor_incomplete",
        "growth_synthetic_comparison",
        "growth_time_invalid",
        "growth_trial_binding_mismatch",
        "growth_trial_incompatible",
        "growth_trial_measurement_incomplete",
        "growth_trial_measurement_mismatch",
        "growth_trial_missing",
        "growth_unaccounted_obligation",
        "growth_undeclared_successor",
        "growth_unfunded_monetary_cost",
        "growth_units_mismatch",
        "growth_units_missing",
        "growth_unknown_due_to_budget",
        "growth_window_invalid",
        "growth_witness_limit",
        "growth_work_deadline",
        "growth_work_duplicate",
        "growth_work_invalid",
    }
)

EPISTEMIC_ERROR_CODES: Final[frozenset[str]] = frozenset(
    {
        "catalogue_candidate_missing",
        "catalogue_certificate_tampered",
        "catalogue_model_only_opt_in_required",
        "catalogue_model_replanned",
        "catalogue_parent_mismatch",
        "catalogue_parent_missing",
        "catalogue_proposal_tampered",
        "catalogue_revision_binding",
        "catalogue_revision_quota",
        "catalogue_search_contradiction",
        "catalogue_synthesis_quota",
        "composition_candidate_binding",
        "composition_candidates_checked",
        "composition_check_budget",
        "composition_constituent_tampered",
        "composition_costs_missing",
        "composition_domain_invalid",
        "composition_endpoint_overrun",
        "composition_grammar_bound",
        "composition_input_binding",
        "composition_interface_type",
        "composition_ir_identity",
        "composition_no_candidate",
        "composition_observation_branch_missing",
        "composition_postcondition",
        "composition_primitive_binding",
        "composition_primitive_budget",
        "composition_primitive_missing",
        "composition_search_unknown",
        "composition_support_tampered",
        "composition_tamper_not_rejected",
        "epistemic_action_excluded",
        "epistemic_action_unknown",
        "epistemic_alphabet_invalid",
        "epistemic_channel_invalid",
        "epistemic_check_budget",
        "epistemic_comparators",
        "epistemic_composition_example",
        "epistemic_continuation_missing",
        "epistemic_cost_deadline",
        "epistemic_cost_event_invalid",
        "epistemic_endpoint_overrun",
        "epistemic_entry_epoch_invalid",
        "epistemic_evidence_binding",
        "epistemic_evidence_incompatible",
        "epistemic_evidence_trace_incomplete",
        "epistemic_example_unknown",
        "epistemic_export_binding",
        "epistemic_export_inputs",
        "epistemic_hidden_branch_not_an_observation",
        "epistemic_hidden_entry",
        "epistemic_history_budget",
        "epistemic_hypothetical_replay",
        "epistemic_inconsistent_support",
        "epistemic_incumbent",
        "epistemic_input_binding",
        "epistemic_kernel_incomplete",
        "epistemic_kernel_invalid",
        "epistemic_measurement_mapping",
        "epistemic_model_switch",
        "epistemic_no_guaranteed_entry",
        "epistemic_objective_tampered",
        "epistemic_observation_branch_missing",
        "epistemic_observation_compatible",
        "epistemic_observation_mismatch",
        "epistemic_observation_not_admitted",
        "epistemic_observation_required",
        "epistemic_original_evidence_unavailable",
        "epistemic_plan_binding",
        "epistemic_policy_checked",
        "epistemic_policy_digest",
        "epistemic_policy_found",
        "epistemic_policy_missing",
        "epistemic_primitive_budget",
        "epistemic_proposed_primitive_job",
        "epistemic_receipt_action",
        "epistemic_receipt_missing",
        "epistemic_replan_evidence_unavailable",
        "epistemic_replay_terminal",
        "epistemic_search_budget",
        "epistemic_search_unknown",
        "epistemic_support_budget",
        "epistemic_support_inspected",
        "epistemic_support_tampered",
        "epistemic_unsigned_replan",
        "information_refinement_basis",
        "information_sensing_actions",
    }
)

ERROR_CATALOG: Final[dict[str, dict[str, object]]] = {
    "authoritative_time_required": {
        "effect_class": "none",
        "recovery": ["Import a trusted-time receipt admitted under the active policy."],
    },
    "bearer_token_required": {
        "effect_class": "none",
        "recovery": ["Set CPCF_TOKEN to a short-lived OIDC access token."],
    },
    "bundle_verification_failed": {
        "effect_class": "none",
        "recovery": ["Re-export the bundle from its authoritative generation."],
    },
    "candidate_set_overflow_unknown": {
        "effect_class": "none",
        "recovery": ["Narrow the signed action registry without dropping safety filters."],
    },
    "control_plane_unavailable": {
        "effect_class": "none",
        "recovery": ["Verify CPCF_API_URL, OIDC authority, and service readiness."],
    },
    "document_schema_invalid": {
        "effect_class": "none",
        "recovery": ["Validate the object against the installed schema digest."],
    },
    "legacy_mutation_blocked": {
        "effect_class": "none",
        "recovery": ["Use cpcf legacy inspect only for a registered read-only command."],
    },
    "offline_self_check_failed": {
        "effect_class": "none",
        "recovery": ["Reinstall the wheel under a supported CPython version."],
    },
    "projection_not_promoted": {
        "effect_class": "none",
        "recovery": ["Reconstruct source pointers and obtain the required independent approval."],
    },
    "quorum_not_satisfied": {
        "effect_class": "none",
        "recovery": ["Obtain role-separated signatures from distinct admitted principals."],
    },
    "unknown_document_kind": {
        "effect_class": "none",
        "recovery": ["Run cpcf schema list --json and select a registered kind."],
    },
    "unsupported_document_version": {
        "effect_class": "none",
        "recovery": ["Inspect legacy content read-only and migrate by copy."],
    },
    **{
        code: {
            "effect_class": "none",
            "recovery": [
                "Inspect the signed lease, capability, execution policy, artifacts, and receipt."
            ],
        }
        for code in sorted(RUNNER_GATEWAY_ERROR_CODES)
    },
    **{
        code: {
            "effect_class": "none",
            "recovery": [
                "Inspect the immutable growth contract, all-prefix ledger, search limits, "
                "and admitted evidence; see docs/growth-planning.md."
            ],
        }
        for code in sorted(GROWTH_ERROR_CODES | EPISTEMIC_ERROR_CODES)
    },
}
