apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-cpcf-api
spec:
  minAvailable: 2
  selector:
    matchLabels: {app.kubernetes.io/name: cpcf-api}
---
{{- if .Values.worker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-cpcf-worker
spec:
  minAvailable: 1
  selector:
    matchLabels: {app.kubernetes.io/name: cpcf-worker}
{{- end }}
