apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cpcf-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cpcf-worker
automountServiceAccountToken: false
{{- if .Values.migration.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cpcf-migration
automountServiceAccountToken: false
{{- end }}
